import streamlit as st

from data_engine import load_csv, prepare_data, validate_data
from strategy_engine import create_strategy, STRATEGY_REGISTRY
from backtest_engine import BacktestEngine

st.set_page_config(page_title="Forex Backtester", page_icon="📊", layout="wide")

LANGUAGES = [
    ("English", "en"), ("العربية", "ar"), ("हिन्दी", "hi"),
    ("Français", "fr"), ("中文", "zh"), ("日本語", "ja"), ("Русский", "ru"),
]

T = {
"en": {"title":"📊 Forex Backtester","subtitle":"Test strategies with next-bar execution and explicit trading costs.","market":"1. Market Data","upload":"Upload OHLC CSV","load":"Load data","loaded":"Loaded {n:,} valid candles","gaps":"Detected {n} possible time gaps.","strategy":"2. Strategy","strategy_name":"Strategy","rr":"Risk / Reward","fast":"Fast EMA","slow":"Slow EMA","execution":"3. Execution","balance":"Initial balance","risk":"Risk per trade (%)","spread":"Spread (pips)","slippage":"Slippage (pips)","commission":"Commission per lot per side","pip":"Pip size","model":"Same-candle SL/TP model","conservative":"Conservative","optimistic":"Optimistic","run":"▶ Run Backtest","no_data":"Upload a CSV containing Open, High, Low and Close columns.","data":"Data","candles":"Candles","first":"First","last":"Last","preview":"Data preview","preparing":"Preparing backtest...","running":"Running backtest... {done:,}/{total:,}","completed":"Completed","success":"Backtest completed.","results":"Results","final":"Final Balance","profit":"Net Profit","trades":"Trades","win":"Win Rate","pf":"Profit Factor","dd":"Max Drawdown","equity":"Equity Curve","no_trades":"No trades were generated by this strategy on this dataset.","download":"Download trades CSV","error":"Error","lang":"Language"},
"ar": {"title":"📊 اختبار استراتيجيات الفوركس","subtitle":"اختبر الاستراتيجيات بتنفيذ الصفقة على الشمعة التالية مع احتساب تكاليف التداول بوضوح.","market":"1. بيانات السوق","upload":"ارفع ملف OHLC CSV","load":"تحميل البيانات","loaded":"تم تحميل {n:,} شمعة صالحة","gaps":"تم اكتشاف {n} فجوات زمنية محتملة.","strategy":"2. الاستراتيجية","strategy_name":"الاستراتيجية","rr":"العائد / المخاطرة","fast":"EMA السريع","slow":"EMA البطيء","execution":"3. التنفيذ","balance":"الرصيد الابتدائي","risk":"المخاطرة لكل صفقة (%)","spread":"السبريد (نقطة)","slippage":"الانزلاق السعري (نقطة)","commission":"العمولة لكل لوت لكل جانب","pip":"حجم النقطة","model":"نموذج SL/TP داخل نفس الشمعة","conservative":"محافظ","optimistic":"متفائل","run":"▶ تشغيل الباك تست","no_data":"ارفع ملف CSV يحتوي على Open وHigh وLow وClose.","data":"البيانات","candles":"الشموع","first":"الأولى","last":"الأخيرة","preview":"معاينة البيانات","preparing":"جارٍ تجهيز الباك تست...","running":"جارٍ تشغيل الباك تست... {done:,}/{total:,}","completed":"اكتمل","success":"اكتمل الباك تست بنجاح.","results":"النتائج","final":"الرصيد النهائي","profit":"صافي الربح","trades":"الصفقات","win":"نسبة الفوز","pf":"معامل الربح","dd":"أقصى تراجع","equity":"منحنى رأس المال","no_trades":"لم يتم توليد أي صفقات بهذه الاستراتيجية على هذه البيانات.","download":"تحميل الصفقات CSV","error":"خطأ","lang":"اللغة"},
"hi": {"title":"📊 फॉरेक्स बैकटेस्टर","subtitle":"अगली कैंडल पर निष्पादन और स्पष्ट ट्रेडिंग लागत के साथ रणनीतियों का परीक्षण करें।","market":"1. मार्केट डेटा","upload":"OHLC CSV अपलोड करें","load":"डेटा लोड करें","loaded":"{n:,} वैध कैंडल लोड हुईं","gaps":"{n} संभावित समय अंतराल मिले।","strategy":"2. रणनीति","strategy_name":"रणनीति","rr":"रिस्क / रिवॉर्ड","fast":"फास्ट EMA","slow":"स्लो EMA","execution":"3. निष्पादन","balance":"प्रारंभिक बैलेंस","risk":"प्रति ट्रेड रिस्क (%)","spread":"स्प्रेड (पिप्स)","slippage":"स्लिपेज (पिप्स)","commission":"प्रति लॉट प्रति साइड कमीशन","pip":"पिप साइज","model":"एक ही कैंडल SL/TP मॉडल","conservative":"कंज़र्वेटिव","optimistic":"ऑप्टिमिस्टिक","run":"▶ बैकटेस्ट चलाएं","no_data":"Open, High, Low और Close वाला CSV अपलोड करें।","data":"डेटा","candles":"कैंडल्स","first":"पहला","last":"अंतिम","preview":"डेटा प्रीव्यू","preparing":"बैकटेस्ट तैयार हो रहा है...","running":"बैकटेस्ट चल रहा है... {done:,}/{total:,}","completed":"पूर्ण","success":"बैकटेस्ट पूरा हुआ।","results":"परिणाम","final":"अंतिम बैलेंस","profit":"नेट प्रॉफिट","trades":"ट्रेड्स","win":"विन रेट","pf":"प्रॉफिट फैक्टर","dd":"अधिकतम ड्रॉडाउन","equity":"इक्विटी कर्व","no_trades":"इस डेटा पर कोई ट्रेड नहीं बना।","download":"ट्रेड्स CSV डाउनलोड करें","error":"त्रुटि","lang":"भाषा"},
"fr": {"title":"📊 Forex Backtester","subtitle":"Testez des stratégies avec exécution sur la bougie suivante et coûts explicites.","market":"1. Données de marché","upload":"Importer un CSV OHLC","load":"Charger les données","loaded":"{n:,} bougies valides chargées","gaps":"{n} écarts temporels possibles détectés.","strategy":"2. Stratégie","strategy_name":"Stratégie","rr":"Risque / Rendement","fast":"EMA rapide","slow":"EMA lente","execution":"3. Exécution","balance":"Solde initial","risk":"Risque par trade (%)","spread":"Spread (pips)","slippage":"Slippage (pips)","commission":"Commission par lot et par côté","pip":"Taille du pip","model":"Modèle SL/TP même bougie","conservative":"Conservateur","optimistic":"Optimiste","run":"▶ Lancer le backtest","no_data":"Importez un CSV contenant Open, High, Low et Close.","data":"Données","candles":"Bougies","first":"Première","last":"Dernière","preview":"Aperçu des données","preparing":"Préparation du backtest...","running":"Backtest en cours... {done:,}/{total:,}","completed":"Terminé","success":"Backtest terminé.","results":"Résultats","final":"Solde final","profit":"Profit net","trades":"Trades","win":"Taux de réussite","pf":"Facteur de profit","dd":"Drawdown maximal","equity":"Courbe d'équité","no_trades":"Aucun trade généré sur ces données.","download":"Télécharger les trades CSV","error":"Erreur","lang":"Langue"},
"zh": {"title":"📊 外汇回测器","subtitle":"使用下一根K线执行和明确交易成本测试策略。","market":"1. 市场数据","upload":"上传 OHLC CSV","load":"加载数据","loaded":"已加载 {n:,} 根有效K线","gaps":"检测到 {n} 个可能的时间缺口。","strategy":"2. 策略","strategy_name":"策略","rr":"风险 / 回报","fast":"快速 EMA","slow":"慢速 EMA","execution":"3. 执行","balance":"初始余额","risk":"每笔风险 (%)","spread":"点差 (pips)","slippage":"滑点 (pips)","commission":"每手每边佣金","pip":"Pip 大小","model":"同一K线 SL/TP 模型","conservative":"保守","optimistic":"乐观","run":"▶ 运行回测","no_data":"上传包含 Open、High、Low 和 Close 的 CSV。","data":"数据","candles":"K线","first":"第一根","last":"最后一根","preview":"数据预览","preparing":"正在准备回测...","running":"正在运行回测... {done:,}/{total:,}","completed":"完成","success":"回测完成。","results":"结果","final":"最终余额","profit":"净利润","trades":"交易","win":"胜率","pf":"盈利因子","dd":"最大回撤","equity":"资金曲线","no_trades":"该策略在此数据上没有产生交易。","download":"下载交易 CSV","error":"错误","lang":"语言"},
"ja": {"title":"📊 Forex Backtester","subtitle":"次の足での約定と明確な取引コストで戦略をテストします。","market":"1. マーケットデータ","upload":"OHLC CSV をアップロード","load":"データを読み込む","loaded":"{n:,} 本の有効な足を読み込みました","gaps":"{n} 件の時間ギャップの可能性を検出しました。","strategy":"2. ストラテジー","strategy_name":"ストラテジー","rr":"リスク / リワード","fast":"高速 EMA","slow":"低速 EMA","execution":"3. 執行","balance":"初期残高","risk":"1取引あたりのリスク (%)","spread":"スプレッド (pips)","slippage":"スリッページ (pips)","commission":"1ロット・片側あたりの手数料","pip":"Pip サイズ","model":"同一足の SL/TP モデル","conservative":"保守的","optimistic":"楽観的","run":"▶ バックテスト実行","no_data":"Open、High、Low、Close を含む CSV をアップロードしてください。","data":"データ","candles":"足","first":"最初","last":"最後","preview":"データプレビュー","preparing":"バックテストを準備中...","running":"バックテスト実行中... {done:,}/{total:,}","completed":"完了","success":"バックテストが完了しました。","results":"結果","final":"最終残高","profit":"純利益","trades":"トレード","win":"勝率","pf":"プロフィットファクター","dd":"最大ドローダウン","equity":"エクイティカーブ","no_trades":"このデータでは取引が生成されませんでした。","download":"取引 CSV をダウンロード","error":"エラー","lang":"言語"},
"ru": {"title":"📊 Forex Backtester","subtitle":"Тестируйте стратегии с исполнением на следующей свече и явными торговыми издержками.","market":"1. Рыночные данные","upload":"Загрузить OHLC CSV","load":"Загрузить данные","loaded":"Загружено {n:,} корректных свечей","gaps":"Обнаружено возможных временных разрывов: {n}.","strategy":"2. Стратегия","strategy_name":"Стратегия","rr":"Риск / Доходность","fast":"Быстрая EMA","slow":"Медленная EMA","execution":"3. Исполнение","balance":"Начальный баланс","risk":"Риск на сделку (%)","spread":"Спред (пипсы)","slippage":"Проскальзывание (пипсы)","commission":"Комиссия за лот за сторону","pip":"Размер пипса","model":"Модель SL/TP в одной свече","conservative":"Консервативная","optimistic":"Оптимистичная","run":"▶ Запустить бэктест","no_data":"Загрузите CSV с Open, High, Low и Close.","data":"Данные","candles":"Свечи","first":"Первая","last":"Последняя","preview":"Предпросмотр данных","preparing":"Подготовка бэктеста...","running":"Выполняется бэктест... {done:,}/{total:,}","completed":"Готово","success":"Бэктест завершён.","results":"Результаты","final":"Итоговый баланс","profit":"Чистая прибыль","trades":"Сделки","win":"Процент выигрышей","pf":"Фактор прибыли","dd":"Макс. просадка","equity":"Кривая капитала","no_trades":"На этих данных стратегия не открыла сделок.","download":"Скачать сделки CSV","error":"Ошибка","lang":"Язык"},
}

for key, value in {"data": None, "result": None, "language": "en"}.items():
    st.session_state.setdefault(key, value)

with st.sidebar:
    lang_labels = [name for name, _ in LANGUAGES]
    current_index = next(i for i, (_, code) in enumerate(LANGUAGES) if code == st.session_state.language)
    selected = st.selectbox("Language / اللغة", lang_labels, index=current_index, key="language_selector")
    st.session_state.language = dict(LANGUAGES)[selected]

lang = st.session_state.language
t = T[lang]
if lang == "ar":
    st.markdown("<style>html,body,[data-testid='stAppViewContainer']{direction:rtl;text-align:right}</style>", unsafe_allow_html=True)

st.title(t["title"])
st.caption(t["subtitle"])

with st.sidebar:
    st.divider()
    st.header(t["market"])
    uploaded = st.file_uploader(t["upload"], type=["csv"])
    if uploaded is not None and st.button(t["load"], use_container_width=True):
        try:
            raw = load_csv(uploaded)
            data = prepare_data(raw)
            report = validate_data(data)
            st.session_state.data = data
            st.session_state.result = None
            st.success(t["loaded"].format(n=len(data)))
            if report.get("missing_bars", 0):
                st.warning(t["gaps"].format(n=report["missing_bars"]))
        except Exception as exc:
            st.error(f"{t['error']}: {exc}")

    st.divider()
    st.header(t["strategy"])
    strategy_name = st.selectbox(t["strategy_name"], list(STRATEGY_REGISTRY.keys()))
    params = {}
    if strategy_name == "Price Action Reversal":
        params["risk_reward"] = st.number_input(t["rr"], 0.1, 20.0, 2.0, 0.1)
    else:
        params["fast_period"] = st.number_input(t["fast"], 2, 500, 20, 1)
        params["slow_period"] = st.number_input(t["slow"], 3, 1000, 200, 1)
        params["risk_reward"] = st.number_input(t["rr"], 0.1, 20.0, 2.0, 0.1)

    st.divider()
    st.header(t["execution"])
    initial_balance = st.number_input(t["balance"], 100.0, 10_000_000.0, 10_000.0, 100.0)
    risk_percent = st.number_input(t["risk"], 0.01, 10.0, 1.0, 0.01)
    spread_pips = st.number_input(t["spread"], 0.0, 100.0, 1.0, 0.1)
    slippage_pips = st.number_input(t["slippage"], 0.0, 100.0, 0.0, 0.1)
    commission = st.number_input(t["commission"], 0.0, 100.0, 0.0, 0.1)
    pip_size = st.number_input(t["pip"], 0.000001, 1.0, 0.0001, format="%.6f")
    model_label = st.selectbox(t["model"], [t["conservative"], t["optimistic"]])
    intrabar_model = "conservative" if model_label == t["conservative"] else "optimistic"
    run = st.button(t["run"], type="primary", use_container_width=True, disabled=st.session_state.data is None)

if st.session_state.data is None:
    st.info(t["no_data"])
else:
    data = st.session_state.data
    st.subheader(t["data"])
    a, b, c = st.columns(3)
    a.metric(t["candles"], f"{len(data):,}")
    a_time = str(data["time"].iloc[0]) if "time" in data.columns else "N/A"
    z_time = str(data["time"].iloc[-1]) if "time" in data.columns else "N/A"
    b.metric(t["first"], a_time)
    c.metric(t["last"], z_time)
    st.line_chart(data.set_index("time")["close"] if "time" in data.columns else data["close"])
    with st.expander(t["preview"]):
        st.dataframe(data.head(100), use_container_width=True)

if run:
    try:
        strategy = create_strategy(strategy_name, **params)
        engine = BacktestEngine(initial_balance=initial_balance, risk_percent=risk_percent,
            spread_pips=spread_pips, slippage_pips=slippage_pips,
            commission_per_lot=commission, pip_size=pip_size,
            intrabar_model=intrabar_model)
        progress = st.progress(0, text=t["preparing"])
        def callback(done, total):
            progress.progress(min(100, int(done / total * 100)), text=t["running"].format(done=done, total=total))
        st.session_state.result = engine.run(st.session_state.data, strategy, callback)
        progress.progress(100, text=t["completed"])
        st.success(t["success"])
    except Exception as exc:
        st.session_state.result = None
        st.exception(exc)

if st.session_state.result is not None:
    result = st.session_state.result
    m = result["metrics"]
    st.divider(); st.subheader(t["results"])
    cols = st.columns(6)
    values = [(t["final"], f"${m['final_balance']:,.2f}"), (t["profit"], f"${m['net_profit']:,.2f}"),
              (t["trades"], m["total_trades"]), (t["win"], f"{m['win_rate']:.1f}%"),
              (t["pf"], "∞" if m["profit_factor"] == float("inf") else f"{m['profit_factor']:.2f}"),
              (t["dd"], f"{m['max_drawdown']:.2f}%")]
    for col, (label, value) in zip(cols, values): col.metric(label, value)
    if not result["equity_curve"].empty:
        st.subheader(t["equity"])
        eq = result["equity_curve"]
        st.line_chart(eq.set_index("time")["equity"] if "time" in eq.columns else eq["equity"])
    st.subheader(t["trades"])
    if result["trades"].empty:
        st.warning(t["no_trades"])
    else:
        st.dataframe(result["trades"], use_container_width=True)
        st.download_button(t["download"], result["trades"].to_csv(index=False).encode("utf-8"), "backtest_trades.csv", "text/csv")
